
CREATE TABLE emp_new  as SELECT * from emp ;
CREATE TABLE dept_new as select * from dept;

ALTER TABLE dept_new MODIFY deptno PRIMARY KEY;

ALTER TABLE emp_new ADD (
	Grade CHAR(1));

ALTER TABLE emp_new ADD CONSTRAINTS emp_noPri PRIMARY KEY(EMPNO) ;

ALTER TABLE emp_new ADD ( CONSTRAINTS emp_dept_fk FOREIGN KEY (DEPTNO) REFERENCES dept_new(deptno));

ALTER TABLE emp_new ADD check(SAL > 750);

ALTER TABLE emp_new MODIFY (SAL number(10,2) NOT NULL);

ALTER TABLE emp_new MODIFY (ENAME VARCHAR2(35));

ALTER TABLE emp_new drop PRIMARY KEY;

DESC USER_CONS_COLUMNS;
select COLUMN_NAME , CONSTRAINT_NAME from USER_CONS_COLUMNS where TABLE_NAME = 'EMP_NEW';

ALTER TABLE emp_new drop CONSTRAINTS emp_dept_fk ;
ALTER TABLE dept_new DISABLE PRIMARY KEY;
ALTER TABLE dept_new ENABLE PRIMARY KEY;

ALTER TABLE dept_new DROP PRIMARY key CASCADE;

CREATE TABLE emp_new1 AS SELECT * FROM emp;
CREATE TABLE dept_new1 AS SELECT * FROM dept;
ALTER TABLE dept_new1 MODIFY deptno PRIMARY KEY;
ALTER TABLE emp_new1 ADD ( CONSTRAINTS emp_dept_fk1 FOREIGN KEY (DEPTNO) REFERENCES dept_new1(deptno));

DROP TABLE dept_new1;
/*
DROP TABLE dept_new1
           *
ERROR at line 1:
ORA-02449: unique/primary keys in table referenced by foreign keys
*/

COMMENT ON TABLE emp IS 'Employee Information of XYZ Company'; 

COMMENT ON COLUMN dept.deptno is 'Unique depart of XYZ Company';

select TABLE_NAME,COMMENTS,COLUMN_NAME from USER_COL_COMMENTS where TABLE_NAME LIKE 'DEPT' and COLUMN_NAME LIKE 'DEPTNO';

select TABLE_NAME,COMMENTS from USER_TAB_COMMENTS where TABLE_NAME = 'EMP';

COMMENT ON TABLE emp IS '';

RENAME EMP TO EMP_CHANGE;

TRUNCATE TABLE EMP_NEW1;

DROP TABLE DEPT_NEW1 CASCADE CONSTRAINTS;

ALTER TABLE EMP_NEW DROP COLUMN Grade;

ALTER TABLE EMP_NEW RENAME COLUMN COMM to COMMISSION;
  
ALTER TABLE EMP_NEW SET UNUSED COLUMN COMMISSION;

DESC USER_UNUSED_COL_TABS;
select TABLE_NAME , COUNT from USER_UNUSED_COL_TABS where TABLE_NAME like 'EMP_NEW';

ALTER TABLE EMP_NEW DROP UNUSED COLUMNS;
